---

# via https://www.spotify.com/de/download/linux/

- name: Add the Spotify repository signing keys to be able to verify downloaded packages
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90

- name: "Add the Spotify repository"
  apt_repository:
    repo: "deb http://repository.spotify.com stable non-free"
    filename: "spotify"
    state: present
    update_cache: "yes"

- name: "Install Spotify"
  apt:
    name: "{{ spotify_package }}"
    state: present
